### ISSUE TITLE
Part 2.2 - Write unit tests for cyclomatic complex functions

### ISSUE THREAD

**Issue by alanihre** [nicklashersen/numpy#12]
Write unit tests for the ten functions with high cyclomatic complexity. For each function a new branch should be created and this branch should then be merged into the branch `coverage-improvement`. FOr each function, for unit tests should be written and a new issue should be created for each function which references this issue. The following should be accomplished for each function (from the assignment):

- Identify the requirements that are tested or untested by the given test suite.
- Document the requirements (as comments).
- Create new test cases as needed to improve branch coverage in the given functions. Can you call the function directly? Can you expand on existing tests? Do you have to add additional interfaces to the system (as public methods) to make it possible to set up test data structures?
- If you have 100 % branch coverage, you can choose other functions or think about path coverage. You may cover all branches in a function, but what does this mean for the combination of branches? Consider the existing tests by hand and check how they cover the branches (in which combinations). -Add tests to increase path coverage, or argue why this is not possible.

**Comment by erikjoh** [comment]
FINALLY
