### ISSUE TITLE
Part 2.3 - Refactoring

### ISSUE THREAD

**Issue by alanihre** [nicklashersen/numpy#13]
From the assignment: 
> You identified functions/methods with high complexity earlier on. Is this complexity really necessary? Is it possible to split up the code into smaller units to reduce complexity? If so, how would you go about this? Document your plan.

The refactoring should then be implemented in such way that it reduces the cyclomatic complexity by 35% according to the following instructions for P+ from the assignment:
> You can refactor existing code such that the cyclomatic complexity of the functions in question is reduced by at least 35 % (for example, by splitting them), and such that you address at least two of the functions with the highest cyclomatic complexity in the previous version of the code base.

For each function an issue should be created which references this issue and a new branch should be created which is then merged into the branch `refactoring`. The documentation should be put in the README.md file.

**Comment by erikjoh** [comment]
Fixed in #86
