### ISSUE TITLE
Doc: Calculate the cyclomatic complexity of five python functions by hand (doc branch)

### ISSUE THREAD

**Issue by nicklashersen** [nicklashersen/numpy#2]
Calculate the cyclomatic complexity of five python functions by hand and add the result to README.md (branch doc). In order to ensure that the calculation is correct another person need to verify the solution. Post the result as a comment to this issue.

**Comment by nicklashersen** [comment]
add_data_files CCN: 13 

Could someone verify this, there's a link to the correct file in issue #7

**Comment by alanihre** [comment]
I get 13 for add_data_files as well.

**Comment by alanihre** [comment]
finalize_options CCN: 17

Could someone verify this, there's a link to the correct file in issue #9.

**Comment by nicklashersen** [comment]
> finalize_options CCN: 17
> 
> Could someone verify this, there's a link to the correct file in issue #9.

I get 17 as well

**Comment by alanihre** [comment]
A description of how to calculate CCN copied from our Slack (in Swedish):

> if…else ökar π med 1
> if..elseif…else ökar π med 2
> while och for ökar π med 1 vardera
> return och raise ökar s med 1 vardera
> assert påverkar inte eftersom den ökar π med 1 och s med 1 så de tar ut varandra
> kom ihåg att räkna med return vid funktionens slut även om det inte finns utskrivet
>
> CCN = π - s + 2

**Comment by UberlyMaxxor** [comment]
add_data_dir CCN: 15

Could someone verify this, there's a link to the correct file in issue #55

**Comment by alanihre** [comment]
> add_data_dir CCN: 15
> 
> Could someone verify this, there's a link to the correct file in issue #55

I get CCN 15 as well.

**Comment by nicklashersen** [comment]
add_data_files CCN: 14 (including implicit return)

**Comment by erikjoh** [comment]
CCompiler_customize CCN: 15

**Comment by alanihre** [comment]
> CCompiler_customize CCN: 15

I get 15 as well.

**Comment by AntonLilja** [comment]
get_paths: CCN 19

**Comment by alanihre** [comment]
> get_paths: CCN 19

I get 19 as well.
