### ISSUE TITLE
Refactor get_paths

### ISSUE THREAD

**Issue by erikjoh** [nicklashersen/numpy#22]
get_paths@663-716@./distutils/system_info.py

Should be refactored so that the CCN is reduced from 20 to 13 (35%).

**Comment by nicklashersen** [comment]
Fixed in PR #33.

The new CCN of get_paths (get_paths@691-728@system_info.py) is 11. This was done by separating parts of the function, thus the new line numbers.

**Comment by alanihre** [comment]
Implemented by PR #33.
