### ISSUE TITLE
Part 0: Onboarding

### ISSUE THREAD

**Issue by alanihre** [nicklashersen/numpy#5]
Answer the following questions in the report and put them in a separate branch to be merged by a PR.

How good is the "onboarding" documentation?

How easily can you build the project? Briefly describe if everything worked as documented or not:
Did you have to install a lot of additional tools to build the software? Were those tools well documented?
Were other components installed automatically by the build script?
Did the build conclude automatically without errors?
How well do examples and tests run on your system(s)?
Do you plan to continue or choose another project?

**Comment by erikjoh** [comment]
Resolved by #17
