### ISSUE TITLE
Doc: [manual] Cyclomatic complexity for add_data_files

### ISSUE THREAD

**Issue by nicklashersen** [nicklashersen/numpy#7]
Manually calculate the cyclomatic complexity for the add_data_files in [misc_util.py](./numpy/numpy/distutils/misc_util.py)

This issue is part of issue #2.

**Comment by alanihre** [comment]
Link in description broken. Working link: [https://github.com/nicklashersen/numpy/blob/develop/numpy/distutils/misc_util.py](https://github.com/nicklashersen/numpy/blob/develop/numpy/distutils/misc_util.py)

**Comment by alanihre** [comment]
Added by PR #8.
